# Settings
# ========
source 'http://rubygems.org'

# Rails
# =====
gem 'rails', '~> 3.0.0'

# Database
gem 'sqlite3'
# gem 'mysql2', '~> 0.2.7'

# Development
# ===========
group :development do
  gem 'rails3-generators'
  gem 'rspec-rails', "~> 2.1"
  # Haml generators
  gem 'hpricot'
  gem 'ruby_parser'
  gem 'rcov'

  # Capistrano
  gem 'capistrano'
  gem 'cap-recipes'
end

# Test
# ====
group :test do
  # Framework
  # gem "rspec"
  # gem 'rspec-rails'

  # Mocking
  # gem 'mocha'

  # Fixtures
  gem 'factory_girl_rails'

  # Matchers/Helpers
  gem 'shoulda'

  # Integration
  # gem 'cucumber-rails'
  # gem 'cucumber'
  # gem 'webrat'

  # Autotest
  gem 'autotest'
  gem 'autotest-rails'
end

# Standard helpers
# ================
gem 'haml'
gem 'compass', '~> 0.10.6'
gem 'fancy-buttons'

# Navigation
gem 'simple-navigation'

# Styling
gem 'lyb_sidebar'
gem 'styleyt'

# Form framework
gem 'formtastic', '~> 1.2.1'

# CRUD
gem 'will_paginate', :git => 'git://github.com/huerlisi/will_paginate.git', :branch => 'rails3'
gem 'inherited_resources'
gem 'has_scope'
gem 'i18n_rails_helpers', '~> 0.9'

# Javascript
gem 'jquery-rails'

# Authentication
gem 'devise', '~> 1.1'

# Authorization
gem 'cancan'

# Date/Time handling
gem 'validates_timeliness', '~> 3.0.0'

# Monitoring
group :production do
  gem 'rack-google_analytics', :require => "rack/google_analytics", :git => 'git://github.com/ambethia/rack-google_analytics.git'
end
